<a href="https://colab.research.google.com/github/wenh08/Python_projects-/blob/main/NYC_Housing_market.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

In [13]:
df = pd.read_csv("/NYCHousingData.csv")
df.head(10)

/tmp/ipykernel_794/3406139592.py:1: DtypeWarning: Columns (11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/NYCHousingData.csv")

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,372,9,NaN,C7,272 EAST 3 STREET,NaN,...,8,1.0,9,"2,021","7,129",1900.0,2,C7,$0,12/15/2025
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,41,NaN,C6,"745 EAST 6TH STREET, 1B",NaN,...,28,0.0,28,"4,542","18,254",1900.0,2,C4,"$540,000",12/17/2025
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,377,50,NaN,C2,"275 EAST 7TH STREET, 3",NaN,...,5,0.0,5,"2,169","6,294",1900.0,2,C2,"$1,250,000",05/27/2026
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,385,38,NaN,C6,"21-23 AVENUE C, 5B",NaN,...,20,2.0,22,"3,315","17,160",1900.0,2,C4,$0,11/11/2025
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,385,50,NaN,C4,240 EAST 2ND STREET,NaN,...,24,0.0,24,"2,623","11,322",1910.0,2,C4,$0,05/29/2026
5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,389,22,NaN,C7,208 EAST 7TH STREET,NaN,...,28,2.0,30,"4,544","19,418",1900.0,2,C7,"$8,600,000",03/09/2026
6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,390,60,NaN,C2,191 EAST 7 STREET,NaN,...,5,0.0,5,"1,080","3,328",1910.0,2,C2,"$4,665,000",03/25/2026
7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,391,59,NaN,C1,299 EAST 8TH STREET,NaN,...,30,0.0,30,"4,508","18,732",1900.0,2,C1,$0,05/19/2026
8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,392,34,NaN,C7,153 AVENUE C,NaN,...,8,1.0,9,"1,909","6,245",1951.0,2,C7,"$6,850,000",05/14/2026
9,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,393,47,NaN,C4,"377 EAST 10TH STREET, 1C",NaN,...,12,0.0,12,"2,370","10,715",1900.0,2,C4,"$129,316",05/11/2026

In [14]:
df.tail(10)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
82566,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,65,NaN,B9,170 DARNELL LANE,NaN,...,2.0,0.0,2.0,"3,060","1,300",1995.0,1,B9,$0,06/03/2026
82567,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,65,NaN,B9,170 DARNELL LANE,NaN,...,2.0,0.0,2.0,"3,060","1,300",1995.0,1,B9,"$860,000",07/01/2026
82568,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,73,NaN,B9,155 DARNELL LANE,NaN,...,2.0,0.0,2.0,"3,117","1,300",1995.0,1,B9,"$725,000",03/31/2026
82569,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,82,NaN,B9,53 DARNELL LANE,NaN,...,2.0,0.0,2.0,"2,327","1,500",1995.0,1,B9,"$775,000",03/09/2026
82570,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,103,NaN,B9,106 DARNELL LANE,NaN,...,2.0,0.0,2.0,"2,900","1,500",1995.0,1,B9,$0,01/22/2026
82571,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7317,19,NaN,B9,10 MANDY COURT,NaN,...,2.0,0.0,2.0,"2,379","1,760",1997.0,1,B9,"$815,000",09/15/2026
82572,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7346,12,NaN,B2,476 HARGOLD AVENUE,NaN,...,2.0,0.0,2.0,"7,933","2,875",1997.0,1,B2,"$1,765,000",05/27/2026
82573,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,NaN,B9,37 QUAIL LANE,NaN,...,2.0,0.0,2.0,"2,400","2,575",1998.0,1,B9,"$885,000",10/22/2025
82574,5,WOODROW,03 THREE FAMILY DWELLINGS,1,6967,12,NaN,C0,999 RATHBUN AVENUE,NaN,...,3.0,0.0,3.0,"2,500","1,440",1987.0,1,C0,$0,01/13/2026
82575,5,WOODROW,04 TAX CLASS 1 CONDOS,1C,7267,"1,001",NaN,R6,"138A CLAY PIT ROAD, 1",1,...,1.0,NaN,1.0,NaN,NaN,2022.0,1,R6,"$890,969",08/25/2026

In [15]:
df.info()
# Here We can see this datset isessy, there's missing values, empty values in columns, datatypes that are incorrect

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82576 entries, 0 to 82575
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BOROUGH                         82576 non-null  int64
 1   NEIGHBORHOOD                    82576 non-null  object
 2   BUILDING CLASS CATEGORY         82576 non-null  object
 3   TAX CLASS AT PRESENT            82576 non-null  object
 4   BLOCK                           82576 non-null  int64
 5   LOT                             82576 non-null  object
 6   EASE-MENT                       0 non-null      float64
 7   BUILDING CLASS AT PRESENT       82576 non-null  object
 8   ADDRESS                         82575 non-null  object
 9   APARTMENT NUMBER                20690 non-null  object
 10  ZIP CODE                        82560 non-null  float64
 11  RESIDENTIAL UNITS               62554 non-null  object
 12  COMMERCIAL UNITS                47950 non-null  float64
 13  TOTAL UNITS                     65644 non-null  object
 14  LAND SQUARE FEET                44860 non-null  object
 15  GROSS SQUARE FEET               44860 non-null  object
 16  YEAR BUILT                      77179 non-null  float64
 17  TAX CLASS AT TIME OF SALE       82576 non-null  int64
 18  BUILDING CLASS AT TIME OF SALE  82576 non-null  object
 19  SALE PRICE                      82576 non-null  object
 20  SALE DATE                       82576 non-null  object
dtypes: float64(4), int64(3), object(14)
memory usage: 13.2+ MB

In [16]:
df.isna().sum()

BOROUGH                               0
NEIGHBORHOOD                          0
BUILDING CLASS CATEGORY               0
TAX CLASS AT PRESENT                  0
BLOCK                                 0
LOT                                   0
EASE-MENT                         82576
BUILDING CLASS AT PRESENT             0
ADDRESS                               1
APARTMENT NUMBER                  61886
ZIP CODE                             16
RESIDENTIAL UNITS                 20022
COMMERCIAL UNITS                  34626
TOTAL UNITS                       16932
LAND SQUARE FEET                  37716
GROSS SQUARE FEET                 37716
YEAR BUILT                         5397
TAX CLASS AT TIME OF SALE             0
BUILDING CLASS AT TIME OF SALE        0
SALE PRICE                            0
SALE DATE                             0
dtype: int64

In [19]:
df[['SALE PRICE', 'TOTAL UNITS', 'LAND SQUARE FEET', 'BOROUGH', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'GROSS SQUARE FEET', 'SALE DATE' ]].head(20)

,SALE PRICE,TOTAL UNITS,LAND SQUARE FEET,BOROUGH,RESIDENTIAL UNITS,COMMERCIAL UNITS,GROSS SQUARE FEET,SALE DATE
0,$0,9,"2,021",1,8,1.0,"7,129",12/15/2025
1,"$540,000",28,"4,542",1,28,0.0,"18,254",12/17/2025
2,"$1,250,000",5,"2,169",1,5,0.0,"6,294",05/27/2026
3,$0,22,"3,315",1,20,2.0,"17,160",11/11/2025
4,$0,24,"2,623",1,24,0.0,"11,322",05/29/2026
5,"$8,600,000",30,"4,544",1,28,2.0,"19,418",03/09/2026
6,"$4,665,000",5,"1,080",1,5,0.0,"3,328",03/25/2026
7,$0,30,"4,508",1,30,0.0,"18,732",05/19/2026
8,"$6,850,000",9,"1,909",1,8,1.0,"6,245",05/14/2026
9,"$129,316",12,"2,370",1,12,0.0,"10,715",05/11/2026
10,"$163,714",12,"2,370",1,12,0.0,"10,715",04/28/2026
11,"$163,715",12,"2,370",1,12,0.0,"10,715",05/11/2026
12,"$8,800,000",11,"2,364",1,8,3.0,"7,166",11/20/2025
13,"$4,275,000",10,"1,449",1,10,0.0,"6,300",04/29/2026
14,$0,21,"2,581",1,21,0.0,"9,150",05/29/2026
15,$0,14,"2,468",1,14,0.0,"10,888",10/02/2025
16,"$2,150,000",18,"2,581",1,16,2.0,"7,230",07/01/2026
17,$0,22,"2,581",1,20,2.0,"9,309",04/20/2026
18,"$7,250,000",22,"2,581",1,20,2.0,"9,309",04/27/2026
19,"$14,150,000",33,"5,746",1,33,0.0,"27,496",07/30/2026